export const ADD_USER = 'ADD_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const EDIT_USER = 'EDIT_USER';
export const REFRESH_USERS = 'REFRESH_USERS';
export const DELETE_USER = 'DELETE_USER';




export const CHANGE_VIEW = 'CHANGE_VIEW';


export const RECEIVE_ALERTS = 'RECEIVE_ALERTS';
export const UPDATE_CURRENT_ALERTS = 'UPDATE_CURRENT_ALERTS';
export const ADD_ALERT = 'ADD_ALERT';
export const REFRESH_ALL_ALERTS = 'REFRESH_ALL_ALERTS';

export const RECEIVE_INTERESTS = 'RECEIVE_INTERESTS';

export const UPDATE_CURRENT_ADDRESS_DETAILS = 'UPDATE_CURRENT_ADDRESS_DETAILS';

export const ADD_ADVOCATE = 'ADD_ADVOCATE';
export const RECEIVE_ADVOCATES = 'RECEIVE_ADVOCATES';
export const SET_CURRENT_ADVOCATE = 'SET_CURRENT_ADVOCATE';
export const CHECK_IN_ADVOCATE = 'CHECK_IN_ADVOCATE';





